### ISSUE TITLE
Setting adapter.log.info to adapter.log.debug

### ISSUE THREAD

**Issue by SurfGargano** [iobroker-community-adapters/ioBroker.tr-064#239]
In (main.js line 723) TR064.prototype.forEachConfiguredDevice = function (callback) {
function doIt() {
there is a adapter.log.info 

adapter.log.info(`forEachConfiguredDevice: in GetSpecificHostEntry ${i - 1}(${dev.name}/${dev.mac}) device seems offline but we never saw it since adapter was started:${err} - ${JSON.stringify(err)}`);
              
This results in many logs entries if devices seems offline.

Can this changed to adapter.log.debug ?

**Comment by Apollon77** [comment]
No we should not change the loglevel in my eyes because it is an relevant info. Maybe we can prevent from "spamming" and just log it from time to time (once an hour)

**Comment by SurfGargano** [comment]
Maybe it is possible to make it as an option in the setup for logic level (info/warn/debug)

**Comment by Apollon77** [comment]
The log is there that the user knows that some data are NOT current when looking at the values because the device was not initialized. Else I can expect issues here because invalid data :-)

If you do not want the log please increase the loglevel of the instance  (Admin - instances - expert mode - column "loglevel")
